//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreateOrderEmex.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchByNumber_Result", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SearchByNumber_Result : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreateOrderEmex.ServiceReference2.PriceDestination[] DestinationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameEngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameRusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PackQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PriceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightGrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitOldNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitSameNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Availability {
            get {
                return this.AvailabilityField;
            }
            set {
                if ((this.AvailabilityField.Equals(value) != true)) {
                    this.AvailabilityField = value;
                    this.RaisePropertyChanged("Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryDays {
            get {
                return this.DeliveryDaysField;
            }
            set {
                if ((this.DeliveryDaysField.Equals(value) != true)) {
                    this.DeliveryDaysField = value;
                    this.RaisePropertyChanged("DeliveryDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreateOrderEmex.ServiceReference2.PriceDestination[] Destinations {
            get {
                return this.DestinationsField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationsField, value) != true)) {
                    this.DestinationsField = value;
                    this.RaisePropertyChanged("Destinations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameEng {
            get {
                return this.DetailNameEngField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameEngField, value) != true)) {
                    this.DetailNameEngField = value;
                    this.RaisePropertyChanged("DetailNameEng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameRus {
            get {
                return this.DetailNameRusField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameRusField, value) != true)) {
                    this.DetailNameRusField = value;
                    this.RaisePropertyChanged("DetailNameRus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNum {
            get {
                return this.DetailNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNumField, value) != true)) {
                    this.DetailNumField = value;
                    this.RaisePropertyChanged("DetailNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PackQuantity {
            get {
                return this.PackQuantityField;
            }
            set {
                if ((this.PackQuantityField.Equals(value) != true)) {
                    this.PackQuantityField = value;
                    this.RaisePropertyChanged("PackQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Percent {
            get {
                return this.PercentField;
            }
            set {
                if ((this.PercentField.Equals(value) != true)) {
                    this.PercentField = value;
                    this.RaisePropertyChanged("Percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceDesc {
            get {
                return this.PriceDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceDescField, value) != true)) {
                    this.PriceDescField = value;
                    this.RaisePropertyChanged("PriceDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PriceId {
            get {
                return this.PriceIdField;
            }
            set {
                if ((this.PriceIdField.Equals(value) != true)) {
                    this.PriceIdField = value;
                    this.RaisePropertyChanged("PriceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceLogo {
            get {
                return this.PriceLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceLogoField, value) != true)) {
                    this.PriceLogoField = value;
                    this.RaisePropertyChanged("PriceLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightGr {
            get {
                return this.WeightGrField;
            }
            set {
                if ((this.WeightGrField.Equals(value) != true)) {
                    this.WeightGrField = value;
                    this.RaisePropertyChanged("WeightGr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitOldNum {
            get {
                return this.bitOldNumField;
            }
            set {
                if ((this.bitOldNumField.Equals(value) != true)) {
                    this.bitOldNumField = value;
                    this.RaisePropertyChanged("bitOldNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitOriginal {
            get {
                return this.bitOriginalField;
            }
            set {
                if ((this.bitOriginalField.Equals(value) != true)) {
                    this.bitOriginalField = value;
                    this.RaisePropertyChanged("bitOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitSameNum {
            get {
                return this.bitSameNumField;
            }
            set {
                if ((this.bitSameNumField.Equals(value) != true)) {
                    this.bitSameNumField = value;
                    this.RaisePropertyChanged("bitSameNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.ComplexObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.PriceDestination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.SearchDetailTender_Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.BalanceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.OrderInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.BasketItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.MakeQuotation_Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.QuotationItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.MakeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.SearchByNumber_Result))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.PriceDestination))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.SearchDetailTender_Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.BalanceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.OrderInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.BasketItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.MakeQuotation_Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.QuotationItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.MakeInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.SearchByNumber_Result))]
    public partial class ComplexObject : CreateOrderEmex.ServiceReference2.StructuralObject {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PriceDestination", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class PriceDestination : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DestinationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DestinationId {
            get {
                return this.DestinationIdField;
            }
            set {
                if ((this.DestinationIdField.Equals(value) != true)) {
                    this.DestinationIdField = value;
                    this.RaisePropertyChanged("DestinationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationLogo {
            get {
                return this.DestinationLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationLogoField, value) != true)) {
                    this.DestinationLogoField = value;
                    this.RaisePropertyChanged("DestinationLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchDetailTender_Result", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class SearchDetailTender_Result : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalanceInfo", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BalanceInfo : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> NewOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> NewOrder {
            get {
                return this.NewOrderField;
            }
            set {
                if ((this.NewOrderField.Equals(value) != true)) {
                    this.NewOrderField = value;
                    this.RaisePropertyChanged("NewOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Orders {
            get {
                return this.OrdersField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdersField, value) != true)) {
                    this.OrdersField = value;
                    this.RaisePropertyChanged("Orders");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Total {
            get {
                return this.TotalField;
            }
            set {
                if ((this.TotalField.Equals(value) != true)) {
                    this.TotalField = value;
                    this.RaisePropertyChanged("Total");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderInfo", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class OrderInfo : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> AmountOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LinesOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumNextOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WeightOrderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> AmountOrder {
            get {
                return this.AmountOrderField;
            }
            set {
                if ((this.AmountOrderField.Equals(value) != true)) {
                    this.AmountOrderField = value;
                    this.RaisePropertyChanged("AmountOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((this.LinesField.Equals(value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LinesOrder {
            get {
                return this.LinesOrderField;
            }
            set {
                if ((this.LinesOrderField.Equals(value) != true)) {
                    this.LinesOrderField = value;
                    this.RaisePropertyChanged("LinesOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> NumNextOrder {
            get {
                return this.NumNextOrderField;
            }
            set {
                if ((this.NumNextOrderField.Equals(value) != true)) {
                    this.NumNextOrderField = value;
                    this.RaisePropertyChanged("NumNextOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> QuantityOrder {
            get {
                return this.QuantityOrderField;
            }
            set {
                if ((this.QuantityOrderField.Equals(value) != true)) {
                    this.QuantityOrderField = value;
                    this.RaisePropertyChanged("QuantityOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> WeightOrder {
            get {
                return this.WeightOrderField;
            }
            set {
                if ((this.WeightOrderField.Equals(value) != true)) {
                    this.WeightOrderField = value;
                    this.RaisePropertyChanged("WeightOrder");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BasketItem", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class BasketItem : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BasketItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CoeffMaxAgreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CustomerSubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_AddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreateOrderEmex.ServiceReference2.PriceDestination[] DestinationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DetailIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameEngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameRusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PackQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceMegaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SubCustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubCustomerPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubcustomerLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UploadedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitAGREEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitConfirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitONLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> bitWaitField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BasketItemId {
            get {
                return this.BasketItemIdField;
            }
            set {
                if ((this.BasketItemIdField.Equals(value) != true)) {
                    this.BasketItemIdField = value;
                    this.RaisePropertyChanged("BasketItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CoeffMaxAgree {
            get {
                return this.CoeffMaxAgreeField;
            }
            set {
                if ((this.CoeffMaxAgreeField.Equals(value) != true)) {
                    this.CoeffMaxAgreeField = value;
                    this.RaisePropertyChanged("CoeffMaxAgree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CustomerSubId {
            get {
                return this.CustomerSubIdField;
            }
            set {
                if ((this.CustomerSubIdField.Equals(value) != true)) {
                    this.CustomerSubIdField = value;
                    this.RaisePropertyChanged("CustomerSubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_Add {
            get {
                return this.Date_AddField;
            }
            set {
                if ((this.Date_AddField.Equals(value) != true)) {
                    this.Date_AddField = value;
                    this.RaisePropertyChanged("Date_Add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationLogo {
            get {
                return this.DestinationLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationLogoField, value) != true)) {
                    this.DestinationLogoField = value;
                    this.RaisePropertyChanged("DestinationLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreateOrderEmex.ServiceReference2.PriceDestination[] Destinations {
            get {
                return this.DestinationsField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationsField, value) != true)) {
                    this.DestinationsField = value;
                    this.RaisePropertyChanged("Destinations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DetailId {
            get {
                return this.DetailIdField;
            }
            set {
                if ((this.DetailIdField.Equals(value) != true)) {
                    this.DetailIdField = value;
                    this.RaisePropertyChanged("DetailId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameEng {
            get {
                return this.DetailNameEngField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameEngField, value) != true)) {
                    this.DetailNameEngField = value;
                    this.RaisePropertyChanged("DetailNameEng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameRus {
            get {
                return this.DetailNameRusField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameRusField, value) != true)) {
                    this.DetailNameRusField = value;
                    this.RaisePropertyChanged("DetailNameRus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNum {
            get {
                return this.DetailNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNumField, value) != true)) {
                    this.DetailNumField = value;
                    this.RaisePropertyChanged("DetailNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PackQuantity {
            get {
                return this.PackQuantityField;
            }
            set {
                if ((this.PackQuantityField.Equals(value) != true)) {
                    this.PackQuantityField = value;
                    this.RaisePropertyChanged("PackQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceLogo {
            get {
                return this.PriceLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceLogoField, value) != true)) {
                    this.PriceLogoField = value;
                    this.RaisePropertyChanged("PriceLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PriceMega {
            get {
                return this.PriceMegaField;
            }
            set {
                if ((this.PriceMegaField.Equals(value) != true)) {
                    this.PriceMegaField = value;
                    this.RaisePropertyChanged("PriceMega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SubCustomerId {
            get {
                return this.SubCustomerIdField;
            }
            set {
                if ((this.SubCustomerIdField.Equals(value) != true)) {
                    this.SubCustomerIdField = value;
                    this.RaisePropertyChanged("SubCustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> SubCustomerPrice {
            get {
                return this.SubCustomerPriceField;
            }
            set {
                if ((this.SubCustomerPriceField.Equals(value) != true)) {
                    this.SubCustomerPriceField = value;
                    this.RaisePropertyChanged("SubCustomerPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubcustomerLogo {
            get {
                return this.SubcustomerLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.SubcustomerLogoField, value) != true)) {
                    this.SubcustomerLogoField = value;
                    this.RaisePropertyChanged("SubcustomerLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UploadedPrice {
            get {
                return this.UploadedPriceField;
            }
            set {
                if ((this.UploadedPriceField.Equals(value) != true)) {
                    this.UploadedPriceField = value;
                    this.RaisePropertyChanged("UploadedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Weight {
            get {
                return this.WeightField;
            }
            set {
                if ((this.WeightField.Equals(value) != true)) {
                    this.WeightField = value;
                    this.RaisePropertyChanged("Weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitAGREE {
            get {
                return this.bitAGREEField;
            }
            set {
                if ((this.bitAGREEField.Equals(value) != true)) {
                    this.bitAGREEField = value;
                    this.RaisePropertyChanged("bitAGREE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitBrand {
            get {
                return this.bitBrandField;
            }
            set {
                if ((this.bitBrandField.Equals(value) != true)) {
                    this.bitBrandField = value;
                    this.RaisePropertyChanged("bitBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitConfirm {
            get {
                return this.bitConfirmField;
            }
            set {
                if ((this.bitConfirmField.Equals(value) != true)) {
                    this.bitConfirmField = value;
                    this.RaisePropertyChanged("bitConfirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitONLY {
            get {
                return this.bitONLYField;
            }
            set {
                if ((this.bitONLYField.Equals(value) != true)) {
                    this.bitONLYField = value;
                    this.RaisePropertyChanged("bitONLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitQuantity {
            get {
                return this.bitQuantityField;
            }
            set {
                if ((this.bitQuantityField.Equals(value) != true)) {
                    this.bitQuantityField = value;
                    this.RaisePropertyChanged("bitQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> bitWait {
            get {
                return this.bitWaitField;
            }
            set {
                if ((this.bitWaitField.Equals(value) != true)) {
                    this.bitWaitField = value;
                    this.RaisePropertyChanged("bitWait");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeQuotation_Result", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CreateOrderEmex.ServiceReference2.QuotationItem))]
    public partial class MakeQuotation_Result : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailabilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DeliveryDaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameEngField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNameRusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PackQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PercentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> PriceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> WeightGrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitOldNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitOriginalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitSameNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Availability {
            get {
                return this.AvailabilityField;
            }
            set {
                if ((this.AvailabilityField.Equals(value) != true)) {
                    this.AvailabilityField = value;
                    this.RaisePropertyChanged("Availability");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DeliveryDays {
            get {
                return this.DeliveryDaysField;
            }
            set {
                if ((this.DeliveryDaysField.Equals(value) != true)) {
                    this.DeliveryDaysField = value;
                    this.RaisePropertyChanged("DeliveryDays");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameEng {
            get {
                return this.DetailNameEngField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameEngField, value) != true)) {
                    this.DetailNameEngField = value;
                    this.RaisePropertyChanged("DetailNameEng");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNameRus {
            get {
                return this.DetailNameRusField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNameRusField, value) != true)) {
                    this.DetailNameRusField = value;
                    this.RaisePropertyChanged("DetailNameRus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNum {
            get {
                return this.DetailNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNumField, value) != true)) {
                    this.DetailNumField = value;
                    this.RaisePropertyChanged("DetailNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PackQuantity {
            get {
                return this.PackQuantityField;
            }
            set {
                if ((this.PackQuantityField.Equals(value) != true)) {
                    this.PackQuantityField = value;
                    this.RaisePropertyChanged("PackQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Percent {
            get {
                return this.PercentField;
            }
            set {
                if ((this.PercentField.Equals(value) != true)) {
                    this.PercentField = value;
                    this.RaisePropertyChanged("Percent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceDesc {
            get {
                return this.PriceDescField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceDescField, value) != true)) {
                    this.PriceDescField = value;
                    this.RaisePropertyChanged("PriceDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> PriceId {
            get {
                return this.PriceIdField;
            }
            set {
                if ((this.PriceIdField.Equals(value) != true)) {
                    this.PriceIdField = value;
                    this.RaisePropertyChanged("PriceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceLogo {
            get {
                return this.PriceLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceLogoField, value) != true)) {
                    this.PriceLogoField = value;
                    this.RaisePropertyChanged("PriceLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> WeightGr {
            get {
                return this.WeightGrField;
            }
            set {
                if ((this.WeightGrField.Equals(value) != true)) {
                    this.WeightGrField = value;
                    this.RaisePropertyChanged("WeightGr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitOldNum {
            get {
                return this.bitOldNumField;
            }
            set {
                if ((this.bitOldNumField.Equals(value) != true)) {
                    this.bitOldNumField = value;
                    this.RaisePropertyChanged("bitOldNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitOriginal {
            get {
                return this.bitOriginalField;
            }
            set {
                if ((this.bitOriginalField.Equals(value) != true)) {
                    this.bitOriginalField = value;
                    this.RaisePropertyChanged("bitOriginal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitSameNum {
            get {
                return this.bitSameNumField;
            }
            set {
                if ((this.bitSameNumField.Equals(value) != true)) {
                    this.bitSameNumField = value;
                    this.RaisePropertyChanged("bitSameNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuotationItem", Namespace="http://schemas.datacontract.org/2004/07/MegaApi.BO", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class QuotationItem : CreateOrderEmex.ServiceReference2.MakeQuotation_Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsQuotationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationLogo {
            get {
                return this.DestinationLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationLogoField, value) != true)) {
                    this.DestinationLogoField = value;
                    this.RaisePropertyChanged("DestinationLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuotation {
            get {
                return this.IsQuotationField;
            }
            set {
                if ((this.IsQuotationField.Equals(value) != true)) {
                    this.IsQuotationField = value;
                    this.RaisePropertyChanged("IsQuotation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeInfo", Namespace="http://schemas.datacontract.org/2004/07/MegaDataLib", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class MakeInfo : CreateOrderEmex.ServiceReference2.ComplexObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCatalogField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductWebsiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeName {
            get {
                return this.MakeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeNameField, value) != true)) {
                    this.MakeNameField = value;
                    this.RaisePropertyChanged("MakeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCatalog {
            get {
                return this.ProductCatalogField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCatalogField, value) != true)) {
                    this.ProductCatalogField = value;
                    this.RaisePropertyChanged("ProductCatalog");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDesc {
            get {
                return this.ProductDescField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductDescField, value) != true)) {
                    this.ProductDescField = value;
                    this.RaisePropertyChanged("ProductDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductInfo {
            get {
                return this.ProductInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductInfoField, value) != true)) {
                    this.ProductInfoField = value;
                    this.RaisePropertyChanged("ProductInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductWebsite {
            get {
                return this.ProductWebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductWebsiteField, value) != true)) {
                    this.ProductWebsiteField = value;
                    this.RaisePropertyChanged("ProductWebsite");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertToBasketItem", Namespace="http://schemas.datacontract.org/2004/07/MegaApi.BO")]
    [System.SerializableAttribute()]
    public partial class InsertToBasketItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CoeffMaxAgreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerStickerDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CustomerSubIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubCustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportPackLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal UploadedPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitAGREEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitConfirmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitONLYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitWaitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CoeffMaxAgree {
            get {
                return this.CoeffMaxAgreeField;
            }
            set {
                if ((this.CoeffMaxAgreeField.Equals(value) != true)) {
                    this.CoeffMaxAgreeField = value;
                    this.RaisePropertyChanged("CoeffMaxAgree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comments {
            get {
                return this.CommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentsField, value) != true)) {
                    this.CommentsField = value;
                    this.RaisePropertyChanged("Comments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrderNumber {
            get {
                return this.CustomerOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderNumberField, value) != true)) {
                    this.CustomerOrderNumberField = value;
                    this.RaisePropertyChanged("CustomerOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerStickerData {
            get {
                return this.CustomerStickerDataField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerStickerDataField, value) != true)) {
                    this.CustomerStickerDataField = value;
                    this.RaisePropertyChanged("CustomerStickerData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CustomerSubId {
            get {
                return this.CustomerSubIdField;
            }
            set {
                if ((this.CustomerSubIdField.Equals(value) != true)) {
                    this.CustomerSubIdField = value;
                    this.RaisePropertyChanged("CustomerSubId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationLogo {
            get {
                return this.DestinationLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationLogoField, value) != true)) {
                    this.DestinationLogoField = value;
                    this.RaisePropertyChanged("DestinationLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNum {
            get {
                return this.DetailNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNumField, value) != true)) {
                    this.DetailNumField = value;
                    this.RaisePropertyChanged("DetailNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceLogo {
            get {
                return this.PriceLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceLogoField, value) != true)) {
                    this.PriceLogoField = value;
                    this.RaisePropertyChanged("PriceLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reference {
            get {
                return this.ReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceField, value) != true)) {
                    this.ReferenceField = value;
                    this.RaisePropertyChanged("Reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCustomerName {
            get {
                return this.SubCustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCustomerNameField, value) != true)) {
                    this.SubCustomerNameField = value;
                    this.RaisePropertyChanged("SubCustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportPackLogo {
            get {
                return this.TransportPackLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportPackLogoField, value) != true)) {
                    this.TransportPackLogoField = value;
                    this.RaisePropertyChanged("TransportPackLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UploadedPrice {
            get {
                return this.UploadedPriceField;
            }
            set {
                if ((this.UploadedPriceField.Equals(value) != true)) {
                    this.UploadedPriceField = value;
                    this.RaisePropertyChanged("UploadedPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitAGREE {
            get {
                return this.bitAGREEField;
            }
            set {
                if ((this.bitAGREEField.Equals(value) != true)) {
                    this.bitAGREEField = value;
                    this.RaisePropertyChanged("bitAGREE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitBrand {
            get {
                return this.bitBrandField;
            }
            set {
                if ((this.bitBrandField.Equals(value) != true)) {
                    this.bitBrandField = value;
                    this.RaisePropertyChanged("bitBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitConfirm {
            get {
                return this.bitConfirmField;
            }
            set {
                if ((this.bitConfirmField.Equals(value) != true)) {
                    this.bitConfirmField = value;
                    this.RaisePropertyChanged("bitConfirm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitONLY {
            get {
                return this.bitONLYField;
            }
            set {
                if ((this.bitONLYField.Equals(value) != true)) {
                    this.bitONLYField = value;
                    this.RaisePropertyChanged("bitONLY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitWait {
            get {
                return this.bitWaitField;
            }
            set {
                if ((this.bitWaitField.Equals(value) != true)) {
                    this.bitWaitField = value;
                    this.RaisePropertyChanged("bitWait");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreQuotationItem", Namespace="http://schemas.datacontract.org/2004/07/MegaApi.BO")]
    [System.SerializableAttribute()]
    public partial class PreQuotationItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MakeLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PriceLogoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CreateOrderEmex.ServiceReference2.QuotationItem QuotationItemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DestinationLogo {
            get {
                return this.DestinationLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationLogoField, value) != true)) {
                    this.DestinationLogoField = value;
                    this.RaisePropertyChanged("DestinationLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetailNum {
            get {
                return this.DetailNumField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailNumField, value) != true)) {
                    this.DetailNumField = value;
                    this.RaisePropertyChanged("DetailNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MakeLogo {
            get {
                return this.MakeLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.MakeLogoField, value) != true)) {
                    this.MakeLogoField = value;
                    this.RaisePropertyChanged("MakeLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PriceLogo {
            get {
                return this.PriceLogoField;
            }
            set {
                if ((object.ReferenceEquals(this.PriceLogoField, value) != true)) {
                    this.PriceLogoField = value;
                    this.RaisePropertyChanged("PriceLogo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CreateOrderEmex.ServiceReference2.QuotationItem QuotationItem {
            get {
                return this.QuotationItemField;
            }
            set {
                if ((object.ReferenceEquals(this.QuotationItemField, value) != true)) {
                    this.QuotationItemField = value;
                    this.RaisePropertyChanged("QuotationItem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateOrder_Result", Namespace="http://schemas.datacontract.org/2004/07/MegaApi.BO")]
    [System.SerializableAttribute()]
    public partial class CreateOrder_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OrderNumber {
            get {
                return this.OrderNumberField;
            }
            set {
                if ((this.OrderNumberField.Equals(value) != true)) {
                    this.OrderNumberField = value;
                    this.RaisePropertyChanged("OrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentId {
            get {
                return this.PaymentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIdField, value) != true)) {
                    this.PaymentIdField = value;
                    this.RaisePropertyChanged("PaymentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.StoreApi")]
    public interface StoreApi {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/echo", ReplyAction="http://tempuri.org/StoreApi/echoResponse")]
        string echo([System.ServiceModel.MessageParameterAttribute(Name="echo")] string echo1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/IsAuth", ReplyAction="http://tempuri.org/StoreApi/IsAuthResponse")]
        bool IsAuth();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/SearchByNumber", ReplyAction="http://tempuri.org/StoreApi/SearchByNumberResponse")]
        CreateOrderEmex.ServiceReference2.SearchByNumber_Result[] SearchByNumber(string detailNum, bool showSubstitution);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/SearchDetailTender", ReplyAction="http://tempuri.org/StoreApi/SearchDetailTenderResponse")]
        CreateOrderEmex.ServiceReference2.SearchDetailTender_Result[] SearchDetailTender(string detailNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetBalanceInfo", ReplyAction="http://tempuri.org/StoreApi/GetBalanceInfoResponse")]
        CreateOrderEmex.ServiceReference2.BalanceInfo GetBalanceInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetSamePartNums", ReplyAction="http://tempuri.org/StoreApi/GetSamePartNumsResponse")]
        string[] GetSamePartNums(string detailNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetOrderInfo", ReplyAction="http://tempuri.org/StoreApi/GetOrderInfoResponse")]
        CreateOrderEmex.ServiceReference2.OrderInfo GetOrderInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetBasket", ReplyAction="http://tempuri.org/StoreApi/GetBasketResponse")]
        CreateOrderEmex.ServiceReference2.BasketItem[] GetBasket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/InsertToBasket", ReplyAction="http://tempuri.org/StoreApi/InsertToBasketResponse")]
        void InsertToBasket(
                    string detailNum, 
                    string makeLogo, 
                    int quantity, 
                    string priceLogo, 
                    string destinationLogo, 
                    string reference, 
                    long customerSubId, 
                    string comments, 
                    bool bitWait, 
                    bool bitConfirm, 
                    bool bitAGREE, 
                    bool bitBrand, 
                    bool bitONLY, 
                    decimal coeffMaxAgree, 
                    decimal uploadedPrice, 
                    string transportPackLogo, 
                    string subCustomerName, 
                    string customerOrderNumber, 
                    string customerStickerData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/InsertBasketItemsToBasket", ReplyAction="http://tempuri.org/StoreApi/InsertBasketItemsToBasketResponse")]
        void InsertBasketItemsToBasket(CreateOrderEmex.ServiceReference2.InsertToBasketItem[] basketItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/UpdateBasket", ReplyAction="http://tempuri.org/StoreApi/UpdateBasketResponse")]
        void UpdateBasket(long basketItemId, int quantity, string destinationLogo, bool bitONLY, bool bitAgree, bool bitWait, bool bitConfirm, bool bitBrand, string reference, long customerSubId, string comments, decimal coeffMaxAgree, decimal uploadedPrice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/DeleteFromBasket", ReplyAction="http://tempuri.org/StoreApi/DeleteFromBasketResponse")]
        void DeleteFromBasket(long basketItemId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/EmptyBasket", ReplyAction="http://tempuri.org/StoreApi/EmptyBasketResponse")]
        void EmptyBasket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/AllToOrderBasket", ReplyAction="http://tempuri.org/StoreApi/AllToOrderBasketResponse")]
        void AllToOrderBasket();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/MakeQuotation", ReplyAction="http://tempuri.org/StoreApi/MakeQuotationResponse")]
        CreateOrderEmex.ServiceReference2.QuotationItem[] MakeQuotation(CreateOrderEmex.ServiceReference2.PreQuotationItem[] preQuotationItems);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetMakeInfoByMakeLogo", ReplyAction="http://tempuri.org/StoreApi/GetMakeInfoByMakeLogoResponse")]
        CreateOrderEmex.ServiceReference2.MakeInfo GetMakeInfoByMakeLogo(string makeLogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/GetMakeInfoList", ReplyAction="http://tempuri.org/StoreApi/GetMakeInfoListResponse")]
        CreateOrderEmex.ServiceReference2.MakeInfo[] GetMakeInfoList(bool bitOriginal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoreApi/CreateOrder", ReplyAction="http://tempuri.org/StoreApi/CreateOrderResponse")]
        CreateOrderEmex.ServiceReference2.CreateOrder_Result CreateOrder();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StoreApiChannel : CreateOrderEmex.ServiceReference2.StoreApi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreApiClient : System.ServiceModel.ClientBase<CreateOrderEmex.ServiceReference2.StoreApi>, CreateOrderEmex.ServiceReference2.StoreApi {
        
        public StoreApiClient() {
        }
        
        public StoreApiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreApiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreApiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreApiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string echo(string echo1) {
            return base.Channel.echo(echo1);
        }
        
        public bool IsAuth() {
            return base.Channel.IsAuth();
        }
        
        public CreateOrderEmex.ServiceReference2.SearchByNumber_Result[] SearchByNumber(string detailNum, bool showSubstitution) {
            return base.Channel.SearchByNumber(detailNum, showSubstitution);
        }
        
        public CreateOrderEmex.ServiceReference2.SearchDetailTender_Result[] SearchDetailTender(string detailNum) {
            return base.Channel.SearchDetailTender(detailNum);
        }
        
        public CreateOrderEmex.ServiceReference2.BalanceInfo GetBalanceInfo() {
            return base.Channel.GetBalanceInfo();
        }
        
        public string[] GetSamePartNums(string detailNum) {
            return base.Channel.GetSamePartNums(detailNum);
        }
        
        public CreateOrderEmex.ServiceReference2.OrderInfo GetOrderInfo() {
            return base.Channel.GetOrderInfo();
        }
        
        public CreateOrderEmex.ServiceReference2.BasketItem[] GetBasket() {
            return base.Channel.GetBasket();
        }
        
        public void InsertToBasket(
                    string detailNum, 
                    string makeLogo, 
                    int quantity, 
                    string priceLogo, 
                    string destinationLogo, 
                    string reference, 
                    long customerSubId, 
                    string comments, 
                    bool bitWait, 
                    bool bitConfirm, 
                    bool bitAGREE, 
                    bool bitBrand, 
                    bool bitONLY, 
                    decimal coeffMaxAgree, 
                    decimal uploadedPrice, 
                    string transportPackLogo, 
                    string subCustomerName, 
                    string customerOrderNumber, 
                    string customerStickerData) {
            base.Channel.InsertToBasket(detailNum, makeLogo, quantity, priceLogo, destinationLogo, reference, customerSubId, comments, bitWait, bitConfirm, bitAGREE, bitBrand, bitONLY, coeffMaxAgree, uploadedPrice, transportPackLogo, subCustomerName, customerOrderNumber, customerStickerData);
        }
        
        public void InsertBasketItemsToBasket(CreateOrderEmex.ServiceReference2.InsertToBasketItem[] basketItems) {
            base.Channel.InsertBasketItemsToBasket(basketItems);
        }
        
        public void UpdateBasket(long basketItemId, int quantity, string destinationLogo, bool bitONLY, bool bitAgree, bool bitWait, bool bitConfirm, bool bitBrand, string reference, long customerSubId, string comments, decimal coeffMaxAgree, decimal uploadedPrice) {
            base.Channel.UpdateBasket(basketItemId, quantity, destinationLogo, bitONLY, bitAgree, bitWait, bitConfirm, bitBrand, reference, customerSubId, comments, coeffMaxAgree, uploadedPrice);
        }
        
        public void DeleteFromBasket(long basketItemId) {
            base.Channel.DeleteFromBasket(basketItemId);
        }
        
        public void EmptyBasket() {
            base.Channel.EmptyBasket();
        }
        
        public void AllToOrderBasket() {
            base.Channel.AllToOrderBasket();
        }
        
        public CreateOrderEmex.ServiceReference2.QuotationItem[] MakeQuotation(CreateOrderEmex.ServiceReference2.PreQuotationItem[] preQuotationItems) {
            return base.Channel.MakeQuotation(preQuotationItems);
        }
        
        public CreateOrderEmex.ServiceReference2.MakeInfo GetMakeInfoByMakeLogo(string makeLogo) {
            return base.Channel.GetMakeInfoByMakeLogo(makeLogo);
        }
        
        public CreateOrderEmex.ServiceReference2.MakeInfo[] GetMakeInfoList(bool bitOriginal) {
            return base.Channel.GetMakeInfoList(bitOriginal);
        }
        
        public CreateOrderEmex.ServiceReference2.CreateOrder_Result CreateOrder() {
            return base.Channel.CreateOrder();
        }
    }
}
